### ISSUE TITLE
dev asset is tried to be loaded in prod env // causes slow page speed

### ISSUE THREAD

**Issue by robertfausk** [pueppiblue/clm#25]
http://localhost:8090/sockjs-node/info?t=1468822187117 is tried to be loaded reglarly on each page.

This causes a slowdown of page speed and results in bad user experience.

To see the error just open console in chrome/firefox

**Comment by pueppiblue** [comment]
Its a conflict with webpack devserver hmr.
Inline mode is added to each entry for hmr.
I will move hmr and devserverconfig to a different .js file.

**Comment by robertfausk** [comment]
- In prod env there is a vendor.js with  file size of 1.5MB. Where does it come from? I don't think that this amount of js is needed.
- How to create assets for prod env? Provide doc would be fine.
- What about open a pull request for this issue if finished?

**Comment by pueppiblue** [comment]
Webpack is adding necessary overhead to all its chunkfiles. But i admit the assets aren't uglified as of yet. --> new Issue
Creating a doc to start webpack for asset creating, will also come with its own issue.

**Comment by robertfausk** [comment]
Ok, so please open a PR for this branch.

Just as small doc for me:

For dev asset generation yo have to start:
```BASH
node dev_server.js
```
